- examples/procfs1.c
- examples/procfs2.c
Since the address of buffer is userspace address, it may triggered a fault on strlen(buffer).
In Ubuntu 20.04.2 LTS ( 5.8.0-63-generic ), using strlen(buffer) will get:
[ 2168.010930] /proc/buffer1k created
[ 2177.014347] BUG: unable to handle page fault for address: 00007fbbc2a17000
[ 2177.014355] #PF: supervisor read access in kernel mode
[ 2177.014358] #PF: error_code(0x0000) - not-present page
[ 2177.014361] PGD 80000003c61d0067 P4D 80000003c61d0067 PUD 3ee6c5067 PMD 40e1ff067 PTE 0
[ 2177.014369] Oops: 0000 [#1] SMP PTI
[ 2177.014376] CPU: 7 PID: 4750 Comm: cat Tainted: P        W  OE     5.8.0-63-generic #71~20.04.1-Ubuntu
[ 2177.014387] RIP: 0010:procfile_read+0xb/0x20 [procfs2]
[ 2177.014393] Code: Unable to access opcode bytes at RIP 0xffffffffc1253fe1.
[ 2177.014396] RSP: …
> Avoid using strlen with the buffer that proc_read function want to write in.

- examples/chardev.c
The name of the device file created in this example is "chardev". 
So  a input command "sudo cat /dev/chardev" to the terminal will surely return a valid message of "I already told you %d times Hello world!"
I'm not sure why author indicates us to check "mycharfile", which wasn't even mentioned in the book.
> Update comment to match this example

- .github/workflows/generate_pdf.yml
Build and release a pdf after every push to master using texlive/texlive docker image.
This PR is meant to be scope limited to serve as a foundation for #15 and #25.
> WIP: Dockerized pdf build in Github Actions

- .github/workflows/generate_pdf.yml
We're using only one tag for release (`latest`), so we have to either replace it correctly or delete it before uploading, otherwise it will fail (https://github.com/ekangmonyet/lkmpg/runs/3213455232):
```
Error: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
```
One possible solution is to use `mknejp/delete-release-assets` to delete existing asset.  If `action-gh-release` supports upserting (https://github.com/softprops/action-gh-release/pull/134), this should only be a **temporary** remedy.  Warning from the `delete-release-assets` repository:
> WARNING
Because this action has the power to delete any asset from any release in the repository (via the access token) be extra careful that you specify the correct tag!
Since it is not really urgent, we …
> Delete existing release asset before releasing

- .gitignore
- Makefile
- html.cfg
- lkmpg.tex
`make4ht` has a lot of defectors:
* When it parsing `lkmpg.tex` and meet `\tableofcontents` will throw error
* When it parsing `lkmpg.tex` and meet url with underscore `\_`, it will output `\_` 
directly instead of `_`
* TOC in generated page isn't as pretty as pdf version
* The `github action` script released by make4ht's team
worked inconsistent  with computer side which causing
error when generating `github page`,and I currently cannot 
find a way to generate `github
page` through `github action` via `make4ht`.
You can see the result page in [here](https://fennecj.github.io/lkmpg/html) currently.
> Generate HTML via make4ht

- .github/workflows/deploy_github_page.yaml
- .github/workflows/generate_doc.yml
Use #20 `makefile` 
1. Generate the HTML assets and deploy them to the [GitHub Page](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)[1].
* Here is the demo URL: https://focaaby.github.io/lkmpg/index.html
2. Publish the `html` directory as release HTML assets.
* Demo download URL: https://github.com/focaaby/lkmpg/releases/download/latest/lkmpg-html.tar.gz
References:
1. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
> Publish GitHub Page with GitHub Action

- lkmpg.tex
In this paragraph,  the file name "proc helloworld" in the second sentance is not consistent with that of the latter sentences. The latter sentences use the file name "/proc/helloworld".
Otherwise, I suggest that the  "the file proc helloworld" in the second sentance should change to "the file proc named helloworld".
> Making the file name "/proc/helloworld" same as others

- lkmpg.tex
In the example "procfs1.c", the "buffer" is actually the second parameter of the function "procfile_read". The "offset" is the fourth parameter. (The first one is "filePointer").
> Update lkmpg.tex context to match the example "procfs1"

- examples/hello-5.c
- lkmpg.tex
For the example module `hello_5`, the book shows the incorrect output which does not correspond to the example input. They are revised here in case to confuse the reader.
Note that I also change `myintArray[2] = {-1, -1}` to `myintArray[2] = {420, 420}`. I think it could make reader clearly reliaze how the command line arguments change the output from the example input.
> Correspond the example output of hello-5.c

- html.cfg
This changes the layout to use the default font size with a reasonable
max width and margins around the body. Elements that would overflow on
narrow displays are changed to wrap (.author) or present a scroll bar as
necessary (figure, .verbatim, .fancyvrb). The properties on html and
body are set such that there is no full-document vertical scrolling.
Inline math is displayed in the same size as the surrounding text.
> Rewrite CSS to support scaling

- lkmpg.tex
Changed `proc_ops` to `file_operations` and also updated its definitions to kernel 5.4 because chap.0.2 install that version.
But I have a question about later chapter.
In chapter 0.7 introduces the /proc file system, use `proc_ops` structure in /proc is fine but that is defined in `linux/proc_fs.h` and you haven't explain it so I may confuse about what is that and the differences between `proc_ops` and `file_operations`.
Related issue: #6
> fix(0.6-proc_ops): changed `proc_ops` to `file_operations`

- Makefile
The _minted-lkmpg directory should be removed AFTER all compile work is
done.
> Remove _minted-lkmpg directory after compiled pdf

- .github/workflows/generate_doc.yaml
According to softprops/action-gh-release#139
Currently the release action version we use has 
bug cause release failed. And we can turn to old
version to make things work again temporarily.
I have tried the latest version from `v0.1.10` to
`v0.1.7`, and `v0.1.8` is the newest version which
worked well when releasing files.
> Temporary fix release action failed issue

- lkmpg.tex
verb warp wrong at line 330 "linux/.config"
> fix minor typo

- lib/codeblock.tex
Added a shorthand way to write inline code blocks.  `\cpp` is added for the inline C code (`\c` is taken - accent), and `\sh` is added for the inline bash code.
> Add ` \cpp` and `\sh` syntax for inline code

- lkmpg.tex
There should be a space between uname and -r
> Fix incorrect path

- lkmpg.tex
This patch is intented to provide detailed info for reference count.
I add sudo lsmod command to provide an alternative way for user to check
the reference count for specific module.
I think `reference count` would be better compared to `use count` so I
replace `use count` with `reference count`.
The paragraph says "there are functions which let you increase,
decrease and display this counter".
But it didn't provide the function to display the the reference counter.
So I add description for module_refcount(THIS_MODULE) as the function
to display the the reference counter.
> Provide detailed info for reference count.

- .gitignore
- Makefile
- examples/bottomhalf.c
- examples/cryptosk.c
- examples/example_tasklet.c
- examples/syscall.c
- lkmpg.tex
Known issues with current example code:
If you using newer kernel(e.g linux 5.11.x) to compile the example code,
you may meet following error:
1. syscall.c:83:50: error: ‘ksys_close’ undeclared;
2. cryptosk.c:17:24: error: field ‘sg’ has incomplete type
3. cryptosk.c:143:9: error: implicit declaration of function
‘get_random_bytes’
4. error: macro "DECLARE_TASKLET" passed 3 arguments, but takes just 2
Solutions/workaround:
1. In syscall.c, replace #include <linux/syscalls.h> with
#include <linux/fdtable.h> and replace  ksys_close with close_fd
if the kernel version >= 5.11. [1][2]
2. Add #include <linux/scatterlist.h> into cryptosk.c
3. Add #include <linux/random.h> into cryptosk.c
4. In bottomhalf.c and example_tasklet.c, replace DECLARE_TASKLET
with DECLARE_TASKLET_OLD and dispose third …
> Update several example code for newer kernel

- examples/syscall.c
- lkmpg.tex
Since the commit 8dbec27a242cd3e2816eeb98d3237b9f57cf6232
(kernel version >= v5.3) the sensitive CR0 bits in x86 is pinned,
we need to use the inline asm to bypass it.
commit 8dbec27a242cd3e2816eeb98d3237b9f57cf6232 :
> With sensitive CR4 bits pinned now, it's possible that the WP bit for
> CR0 might become a target as well.
>
> Following the same reasoning for the CR4 pinning, pin CR0's WP
> bit. Contrary to the cpu feature dependend CR4 pinning this can be done
> with a constant value.
Also, getting `sys_call_table` from memory search by using the address of
`close_fd` does not work for kernel version >= 5.11. The Reason is the entry
of `sys_call_table[__NR_close]` is not the address of `close_fd`, actually
it is `__x64_sys_close` in x86. I provide two solutions, using …
> Fix disable write cr0 protection and close_fd

- examples/bottomhalf.c
- examples/chardev.c
- examples/chardev2.c
- examples/completions.c
- examples/cryptosha256.c
- examples/cryptosk.c
- examples/example_mutex.c
- examples/example_rwlock.c
- examples/example_spinlock.c
- examples/example_tasklet.c
- examples/ioctl.c
- examples/kbleds.c
- examples/procfs1.c
- examples/procfs2.c
- examples/procfs3.c
- examples/sleep.c
- examples/stop.c
- examples/syscall.c
Sparse is a semantic parser of C language.
It can be used to find out the potential
problems of kernel code.
* https://www.kernel.org/doc/html/latest/dev-tools/sparse.html
The warnings:
```shell
$ make C=2
make -C /lib/modules/5.11.0-27-generic/build M=/lkmpg/examples modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-27-generic'
CC [M]  /lkmpg/examples/hello-1.o
CHECK   /lkmpg/examples/hello-1.c
CC [M]  /lkmpg/examples/hello-2.o
CHECK   /lkmpg/examples/hello-2.c
CC [M]  /lkmpg/examples/hello-3.o
CHECK   /lkmpg/examples/hello-3.c
CC [M]  /lkmpg/examples/hello-4.o
CHECK   /lkmpg/examples/hello-4.c
CC [M]  /lkmpg/examples/hello-5.o
CHECK   /lkmpg/examples/hello-5.c
CC [M]  /lkmpg/examples/start.o
CHECK   /lkmpg/examples/start.c
CC [M]  /lkmpg/examples/stop.o
CHECK …
```
> Fix the warnings raised by Sparse

- examples/chardev.c
- examples/chardev2.c
- examples/sleep.c
- lkmpg.tex
In chardev.c, chardev2.c and sleep.c files, the variable to
determine the exclusive access is an integer type, which leads
to the race condition.
In chardev.c and chardev2.c files, change the integer type of
"open_device_cnt" into atomic type.
In sleep.c, the integer type of "already_open" should also be atomic type.
And all the related operations are modified to atomic operations.
The reason why it is unnecessary to change the read operation is
`open_device_cnt` already prevents multiple access.
- sysprog21/lkmpg: https://github.com/sysprog21/lkmpg/issues/93
> Avoid unexpected concurrent access

- html.cfg
Related issue #82 
This new foreground + background color maintains the minimum of 7:1 contrast ratio as specified by WCAG (this has 7.36:1) and is the same colors firefox reading mode uses when choosing the sepia theme. 
Fonts are too small by default, using responsive units (em) let's me increase them, I am unsure where or if there is font-size specified for parent anywhere but it seems to have been manually decreased.
Increased max-width slightly to adjust for new size and more standard line-height, so the doc doesn't feel significantly longer, still maintains good eye travel.
> Improve readability

- html.cfg
p + pre remains at em as we want to use the parent element here (however rem could be used too, just requires a bigger value). I am setting it to 110% size otherwise some codeblocks have relatively small text. The smaller codeblocks do appear bigger but I do not think that they are TOO big, let me know what you think. This is unchanged from before this commit.
> Work around inconsistent text scaling

- examples/kbleds.c
- lkmpg.tex
Since v4.14[1], the timer API started to change.
The series of improvements ended up at v4.15[2].
We have to update the API.
Related article: https://lwn.net/Articles/735887/
[1] https://github.com/torvalds/linux/commit/686fef928bba6be13cabe639f154af7d72b63120
[2] https://github.com/torvalds/linux/commit/841b86f3289dbe858daeceec36423d4ea286fac2
> Adapt timer API usage

- .ci/non-working
Since #98 has fixed the error with kbleds caused by changed timer API,
now it can work again with docker container.
> Remove kbleds from non-working list

- examples/ioctl.c
The "alloc_chrdev_region" function will dynamically choose the
major number and store it at "dev". It is unnecessary to initialize
the "dev" before the "alloc_chrdev_region" function.
> ioctl.c: Remove unnecessary initialization

- .ci/static-analysis.sh
- .github/workflows/generate_doc.yaml
- examples/example_atomic.c
- examples/ioctl.c
Use Cppcheck[1], the static analysis tool, to verify the example codes.
Since Cppcheck has the false-positive and we have to suppress those
warnings sometimes. So, we have to provide the list to display the
suppressed warning for the clarity of maintenance.
[1] https://cppcheck.sourceforge.io/
- sysprog21/lkmpg: : https://github.com/sysprog21/lkmpg/issues/99
> CI: Add Cppcheck to verify the code

- lkmpg.tex
Parameters are case-sensitive, so `myintArray` is different from `myintarray`, and people who are running the example with copy/paste will find it doesn't work as described in the text.  It is all lower-case in the code, so adjusted the example runs to match.
> Fixed parameter name for hello-5.

- examples/chardev.c
- examples/chardev2.c
- lkmpg.tex
Even though the concurrent access to the module has been fixed at commit 148fb01,
the function of device operations can be called concurrently.
In chardev2.c, the message buffer can be simultaneously accessed by the read and
write operations. It can solve by allowing only one of the operations to work at
the time.
In chardev.c, the msg_ptr is the global variable. Therefore, when someone is
concurrently using the read operation will lead to a data race.
The pointer can change into the local variable of the read operation. So, each
read operation will not use the same pointer at the same time.
---
Edited:
Since Linux v3.14, the read, write and seek operations of struct files are
guaranteed for thread safety [1][2]. This patch adds an explanation.
Following are the trivial problems:
- …
> Add the description about some file ops and fix several problems

- .github/workflows/generate_doc.yaml
The action we used to delete the old release somehow cannot find the
release tag in forked repo and cause the workflow failed.
To solve this issue, simply setting `fail-if-no-release` option to false
will do the trick.
The example of failed workflow:
https://github.com/FennecJ-Test/lkmpg/runs/3696212913?check_suite_focus=true
After setting `fail-if-no-release` option to false, it can work well:
https://github.com/FennecJ-Test/lkmpg/runs/3696371773?check_suite_focus=true
By the way, I noticed that `set -x` in `.ci/check-format.sh` caused the output of the workflow log to be a little complicated.
Was the option set on purpose?
> Keep workflow running even if no release tag found

- lkmpg.tex
Shell commands of "sudo insmod hello-5.ko" and "sudo rmmod hello-5" will not display the messages on console. Instead, the pr_info messages shall be displayed with dmesg or journalctl commands only. So update the commands accordingly. To answer to [issue#111](https://github.com/sysprog21/lkmpg/issues/111#issue-1002892953)
> update commands to display hello-5.ko console messages

- lkmpg.tex
Correct English gramma
Original text : within "because at that time, the files you need will be are ready.",  "will be" is redundant.
Corrected text : "because at that time, the files you need are ready."
> Correct English gramma

- .ci/static-analysis.sh
- examples/kbleds.c
- examples/procfs2.c
Smatch[1][2] is a pluggable static analysis for C. It may help us find
out the potential problem of the example code.
Doing with smatch, if set the --file-output flag, it will generate the
{}.c.smatch report for each c file. This will make a little bit
complicated to collect all the report messages. So, here we stay at the
default setting, stdout for the smatch messages.
For more information, see:
- https://lwn.net/Articles/696624/
- https://elinux.org/images/d/d3/Bargmann.pdf
Also, fix the warning from Smatch:
Smatch failed: 1 warning(s), 1 error(s)
/home/runner/work/lkmpg/lkmpg/examples/procfs2.c:57 procfile_write() error: buffer overflow 'procfs_buffer' 1024 <= 1024
/home/runner/work/lkmpg/lkmpg/examples/kbleds.c:58 kbleds_init() warn: argument 5 to %lx specifier is cast from pointer …
> CI: Evaluate Smatch for static analysis

- lkmpg.tex
The Figure 1. was located in procfs4.c sample code.
Which make the sample code be fragmented, and hard to read.
Puting the Figure 1. at the same place it occurs in source text.
> 7.4: adjust the position of Figure 1.

- .mailmap
- contrib.tex
- lkmpg.tex
- scripts/Contributors
- scripts/Exclude
- scripts/Include
- scripts/list-contributors.sh
This script do mainly 2 things:
1.
Generate file `Contributors` with git log in following format:
Contributor's name,<1-st e-mail>[,<2nd e-mail>][,<3rd e-mail>]...
The 2-nd email and so on are based on file `.mailmap` in the root
directory of the repo.
Note that it will also append contributors in File `Include`; and
will NOT append contributors in File `Exclude`.
If there are new contributors, script will sort `Contributor` after
append new contributors into each file; Otherwise it do nothing.
2.
Generate contrib.tex based on `Contributors` into lib/contrib.tex in
following format:
[name], (reasonable width) % [1-st e-mail]
Which is inspired by The Not So Short Introduction to Latex 2e[1]
We need to maintain `.mailmap`, `Exclude` and `Include` manually.
All Chinese name should be …
> Generate contributor list as a modular inclusion

- lkmpg.tex
When I am using this book, I found that the book seems only introduced the char device registration using the older `register_chrdev` / `unregister_chrdev` API. I think we should introduce the cdev interface which is newer and would be better for new driver programmers in most cases. This commit is trying to give the brief overview and also provide comparable codes between two different interfaces.
There may be many insufficient and looking for discussion to change/improve it: 
1. I'm not sure the sentences in the book are enough to introduce the concept, or I should give more explanation.
2. The codes for the old and the new are separated into different files. This produces duplicate codes although make me easy to do those ci(static analysis and build) test. I'm not sure if you would …
> Introduce the new method for chardev registration

- examples/chardev.h
- examples/other/userspace_ioctl.c
- lkmpg.tex
Previously ioctl.c is a userspace program for chardev2.c and chardev.h [1].
But now, this file is an independent kernel module, and the original code
disappear.
This patch adds back the original userspace code and renames it to
userspace_ioctl.c.
Close #138
[1] https://tldp.org/LDP/lkmpg/2.4/html/x856.html
* sysprog21/lkmpg: https://github.com/sysprog21/lkmpg/issues/138
> ioctl, chardev2: Fix incoherent example code

- examples/ioctl.c
Change the `alloc_ret` and `cdev_ret` initial values to non-zero, or it
will `cdev_del()` uninitialized and not-yet-added `test_ioctl_cdev` after
`alloc_chrdev_region()` failed.
> Fix a logic error in examples/ioctl.c

- examples/bottomhalf.c
- examples/chardev.c
- examples/example_tasklet.c
- examples/print_string.c
Replaced 'a' with 'an' since a vowel sound is after.
> Fix typo, grammar and remove duplicated words

- examples/syscall.c
Presently, the representation of showing which version will use the
method to find out the system call table is vague.
This patch improves the description.
* sysprog21/lkmpg: https://github.com/sysprog21/lkmpg/pull/142
> Improve the description of finding syscall table

- .gitignore
- Makefile
- README.md
The current Makefile is missing one more `pdflatex` pass.
The correct steps are : `pdflatex -> bibtex -> pdflatex -> pdflatex` as shown in the reference [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes). 
Otherwise, bib items will not be showing properly.
`.gitignore` has been updated accordingly.
> Use latexmk instead of pdflatex for PDF generation

- examples/vinput.c
- examples/vinput.h
- examples/vkbd.c
- lkmpg.tex
The description of the attribute was added in sysfs section and referenced in vinput section.
In vinput section, just described the class_attribute and some macros about sysfs class.
Add file name at vinput-related examples begin.
> Add description of sysfs attribute

- lkmpg.tex
Both module_init and module_exit are defined in
include/linux/module.h
> module_init and module_exit are defined in module.h

- lkmpg.tex
Currently, in 13.2 Flashing keyboard LEDs, the description of the
control-flow integrity, "Furthermore, the function prototype with
unsigned long argument may be an obstacle to the control-flow integrity
.", will confuse the reader.
It may lead the reader to think about hardware-assisted CFI like Intel
CET uses the shadow stack attack for ROP (backward-edge protection). But
the description of CFI here talks about the function pointer checking
with the prototype (forward-edge protection).
So add more information to make it more clear.
Close #151
> Add more information about the CFI of timer API

- lkmpg.tex
Since the init function may be interrupted. Tweak the description of
"in the mean time".
Close #152
> Adjust "in the mean time" description of tasklet

- README.md
I am a Macbook user and tried to generate the book from the source code.
During the installation process, I found that package Pygments is required and not mentioned in README.md.
I made modifications slightly to highlight the potential building error, please check.
Signed-off-by: Cheng-En Lee <chengenl@usc.edu>
> Add additional macos installation instruction in README.md

- examples/chardev.c
- examples/chardev2.c
Since The length of the message buffer is BUF_LEN. When writing the BUF_LEN length of the string it will overwrite the last character (usually it is '\0' from the initialization). And, because the read operation uses the character in the message buffer ('\0') to stop the read loop. It will cause the read operation will read out of the message buffer when the length parameter of read() is not lower than or equal to BUF_LEN.
---
* https://github.com/sysprog21/lkmpg/issues/158
> Fix the buffer length may cause a read error

- lkmpg.tex
Currently, the description of the proc_ops in the file operation section will confuse the reader with registering the device. Add more hints to avoid it.
---
* https://github.com/sysprog21/lkmpg/issues/158
> Improve the description of proc in file-ops

- examples/procfs2.c
- examples/procfs3.c
To make sure the behavior of the read and write operations are correct with offset, update it each time. Also, since it is using the offset, modify the part of read for removing unnecessary variable.
---
* https://github.com/sysprog21/lkmpg/issues/158
> procfs{2, 3}: Change to use offset parameter

- examples/procfs3.c
min()/max() splited from kernel.h to minmax.h since v5.10-rc1. Before v5.10, minmax.h doesn't exist [1].
[1] https://github.com/torvalds/linux/commit/b296a6d53339a79082c1d2c1761e948e8b3def69
> Improve the compatibility with kernel < v5.10

- examples/sleep.c
Since the operations are static storage duration, the pointer in operation structures will initialize with NULL. But, the kernel doesn't check whether the pointer is NULL or not when calling it.
Related Discussion:
- https://github.com/sysprog21/lkmpg/issues/165
- https://github.com/sysprog21/lkmpg/issues/160
Close #165
> Fix dereference NULL pointer with proc_lseek

- lkmpg.tex
in the hope ... will -> in the hope that ... would
get -> got
where are ... gone -> where have ... gone
For those not -> For those who are not
> Fix grammar

- lkmpg.tex
Changed "The choose ..." to "The choice ..."
> fixed typo (line 1019)

- examples/vinput.c
Fix the missing error code when register_chrdev() failed. The report is from Smatch:
```
Smatch failed: 1 warning(s), 0 error(s)
/home/runner/work/lkmpg/lkmpg/examples/vinput.c:372 vinput_init() warn: missing error code 'err'
```
> vinput: Fix missing error code

- lkmpg.tex
I create a topic branch and hope this time could go more smoothly
> Convey secure boot specific considerations

- lkmpg.tex
%s/assembler/assembly language/
Signed-off-by: Yu Chien Peter Lin <peterlin.tw@pm.me>
> Fix typo in interrupt handlers section

- examples/syscall.c
- lkmpg.tex
Since sys_open is deprecated and some architectures don't support it. We switch the implementation to sys_openat.
Moreover, in some architectures like x86-64, the prototype of syscall, for example, openat(), might have been changed to struct pt_regs [1] but we cannot promise that so support the two types (sys_openat and pt_regs).
Also, to prevent other untraced tasks print out the information, add the uid checking in our_sys_openat().
[1] https://lore.kernel.org/lkml/20180405095307.3730-1-linux@dominikbrodowski.net/
Close #159
> syscall: Use openat() instead of open()

- examples/bottomhalf.c
- examples/chardev.c
- examples/chardev2.c
- examples/completions.c
- examples/devicemodel.c
- examples/example_atomic.c
- examples/example_mutex.c
- examples/example_rwlock.c
- examples/example_spinlock.c
- examples/example_tasklet.c
- examples/hello-1.c
- examples/hello-2.c
- examples/hello-3.c
- examples/hello-4.c
- examples/hello-5.c
- examples/intrpt.c
- examples/sleep.c
- lkmpg.tex
We do not want to encourage people to use garbage which is kernel.h. The rule of thumb is to include the headers we are the direct users of. Clean up a bit the examples and text  of the book.
**UPDATE**
Besides that the examples have rather random headers. This has to be revisited and updated. In this PR it's a subset of the fixes of the mess.
> Discourage kernel.h usage and other header cleanups

- lkmpg.tex
Since the commit b8780c363d80 ("sched: remove sleep_on() and friends "), the description about sleep_on is incorrect and the example code has been fixed by replacing it with wait_event family. Let's also fix the description to match the corrected code.
Close #197
> Remove sleep_on family

- .ci/static-analysis.sh
Since the Smatch repository is unavailable recently [1], let's switch to GitHub mirror, https://github.com/error27/smatch.git [2], instead of using https://repo.or.cz/smatch.git.
[1] https://lore.kernel.org/all/Y1qf7w%2Fjo8FH5I8G@kadam/
[2] https://lore.kernel.org/all/20220810105926.GS3460@kadam/
Close #201
> CI: Switch Smatch source code to GitHub mirror

- examples/Makefile
- examples/static_key.c
- lkmpg.tex
The example kernel module (static_key.c) has been tested on Linux 5.10.x (x86_64) and 6.1.x (riscv64), one can insert this module to observe how the kernel patches the NOP/JMP instructions during run-time with GDB thru Jtag on system, or using QEMU debugging mode.
> Introduce static key in optimizations section

- .github/workflows/build-deploy-assets.yaml
This PR removes a redundant step from existing workflow and addresses a minor issue when publishing a "nightly" release using the current workflow.
Since softprops/action-gh-release#134 is upstreamed, #29 is no longer needed and is reverted as the assets file can be replaced correctly.  Note that the current behavior of the action will remove all existing assets and replace it with **only** the files listed.
Currently, the release body and timestamp is not updated due to the *update-or-create* logic, and it is not possible to update the timestamp of a release using any existing Github API without recreating the release (related issue: softprops/action-gh-release#171).  The release body is not updated as the tag already exists thus the current commit will not be re-tagged.  Removing both …
> Cleanup redundant workflow step, fix release body and timestamp

- examples/static_key.c
Add this include for the static key macros.
> Add `#include<linux/jump_label.h>` to static_key.c

- examples/procfs2.c
- examples/procfs3.c
- examples/procfs4.c
- examples/sleep.c
I found it unneccesary to call `proc_remove` or `remove_proc_entry` when `proc_create` returns NULL.
I searched through kernel and found existing code never call remove on failed creates.
I read the kernel source of drivers/input/input.c
> procfs: Remove unnecessary cleanup on proc_create failure

- examples/kbleds.c
Since the commit 5052df99d3bc ("tty: remove TTY_DRIVER_MAGIC") [1], the magic field no longer exists in the tty_driver. Instead of printing the magic field, use the driver_name field.
[1] https://lore.kernel.org/linux-doc/20220907231109.htnfxzmr6wkuhn2v@tarta.nabijaczleweli.xyz/
Close #216
Close #217
> kbleds: Replace magic with driver_name

- README.md
From the [disscussion](https://bbs.archlinux.org/viewtopic.php?pid=2105974#p2105974), the `latexmk` has been moved to the `texlive-binextra` package.
> Update dependencies for Arch Linux

- examples/chardev.c
- From v6.4, class_create() does not have module *
(See commit 11ba11 below)
- Added #ifdev for KERNEL_VERSION >= 6.4
From linux commit aaba11da9aa7d7d6b52a74d45b31cac118295a1
---------------------------------------------
driver core: class: remove module * from class_create()
The module pointer in class_create() never actually did anything,
and it shouldn't have been requred to be set as a parameter even
if it did something.  So just remove it and fix up all callers of the
function in the kernel tree at the same time.
> Remove module * parameter from class_create()

- .ci/static-analysis.sh
Because of sparse-latest.tar.gz has not been updated since 06-Sep-2021, we are encoutering an old bug, 0e1aae55e49c ("fix "unreplaced" warnings caused by using typeof() on inline functions") [1], that has been fixed in the newest version. So, let's switch to the git source tree [2] instead of using sparse-latest.tar.gz [3].
[1] https://git.kernel.org/pub/scm/devel/sparse/sparse.git/commit/?id=0e1aae55e49cad7ea43848af5b58ff0f57e7af99
[2] git://git.kernel.org/pub/scm/devel/sparse/sparse.git
[3] http://www.kernel.org/pub/software/devel/sparse/dist/sparse-latest.tar.gz
> CI: Fix "unreplaced" warnings by using git source

- examples/ioctl.c
ioctl-number.rst in Documentation has been renamed and moved since v5.10
See commits
- 049500715e7
- 08536105d93
> Correct name/location for ioctl-number.rst

- examples/chardev2.c
From v6.4, class_create() does not have module *
Same as (#222), commit 0addb868dc55 to chardev.c
> Remove module * parameter from class_create() 

- examples/completions.c
- lkmpg.tex
Draft PR looking for review and feedback.
Two struct completion(s) are encapsulated within another 'struct machine'. Simplify the code by removing the outer struct and let the struct completion(s) be self-standing.
For demonstrating an example, I believe the simpler code is better and does just as well. I am not sure if the encapsulation is necessary. Simplifying makes it easier to read and learn from.
> Simplify code by removal of outer struct encapsulating struct completions

- examples/example_atomic.c
dmesg only flushes when it encounter a newline. Without a newline, the line is held in memory pending another printk. In this particular example (example_atomic.c), the last pr_info in atomic_bitwise() prints when another printk happens (either by another module, or __exit for this module.
This can be confusing to new learner. This patch adds a newline to the last pr_info forcing dmesg to print to the screen when the module is loaded.
--------------- Alternate solution ---------------
Alternate solutions could be adding a newline to BYTE_TO_BINARY_PATTERN
#define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c\n"
... or adding a newline to each pr_info() call.
> Add newline to last pr_info to force dmesg to flush

- lkmpg.tex
The word 'defator' is unable to be found in a lexicon. Change the word 'defator' with 'drawbacks' which should imply the negative meaning intended in the sentence.
> Change word in tasklet description

- examples/sched.c
schedule_work adds work to global workqueue. In this example, we create a local workqueue. Use the local workqueue by calling queue_work(), instead of putting work on the global workqueue.
> Replace schedule_work with queue_work

- examples/bottomhalf.c
- examples/procfs4.c
Change 'untill' to 'until' in a comment.
Change 'compatibiity' to 'compatibility' in a comment.
> Fix typo in examples' comments

- lkmpg.tex
Fix procf_read to procfs_read
Closes #242
> Fixed Typo : Close #242

- .ci/check-format.sh
- .ci/static-analysis.sh
A lot of distributions are emitting warnings when using egrep and fgrep since these are deprecated.
Update occurrences of egrep to 'grep -E' keeping the same functionality and making the code more portable without emitting warnings.
> Change occurrences of egrep to grep -E

- examples/cryptosk.c
The code `case -EINPROGRESS || -EBUSY: ` is the same as `case -115 || -16 :` at compiler time, as both error code are implemented with macro like `#define EBUSY 16`. 
The code above is essentially the same as `case 1:`. In C, there is no real boolean value. Bool-like value will be converted to 1 or 0.
It does not matter too much if the `-EINPROGRESS || -EBUSY` is calculated at build time or at runtime. In both case, it will compare the `rc` with `1` in the switch expression. It will not compare the `rc` with any real error code number. When the code is really `-EBUSY`, the execution will fallback to the default branch.
And in practice, most of the compilers will do this simple compile-time static calculation, and generate code like 
```
static int test_skcipher_result(struct skcipher_def …
```
> Fix switch-case condition error in sample code

- examples/bh_threaded.c
- lkmpg.tex
Rework descriptions for threaded IRQ, making it a section of its own. Also, fix errors in the `bh_threaded.c` example.
> Rework the threaded IRQ examples

- lkmpg.tex
Add `\cpp` before |main()| to improve readibility so that it won't look like "|main()|" in the paragraph.
> Improve readibility

- examples/vinput.c
Fix multiple issues for vinput module:
1. Removes redundant memset calls that were unnecessary since memory allocated with kzalloc is already zeroed due to the __GFP_ZERO gfp flag.
2. Fixes a NULL pointer dereference caused by failed kzalloc allocation. It adds a check for the return value of kzalloc and handles failed allocations by printing an error message and returning ERR_PTR(-ENOMEM).
3. Corrects the handling of failures in raw_copy_to_user() in vinput_read(). Previously, the function would modify '*offset' incorrectly on raw_copy_to_user() failure. Fix this behavior by changing count = -EFAULT to return -EFAULT instead.
> vinput: Fix multiple issue

- lkmpg.tex
7.4 The seq_file is missing the behavior that occurs when it directly returns NULL after the start step.
Also, in the flowchart, the first decision where `return is NULL` is `Yes` points to nothing, which is not defined in ISO 5807.
ISO 5807 section 10.3.1.2 states logic path of a decision, "Each exit from a symbol be accompanied by the appropriate condition values to show the logic path which it represents, so that the conditions and the associated references are identified."
The behavior of pointing to nothing does not have associated references and does not indicate the relation of this logic path.
Refs:
1. The Liunx Kernel Module Programming Guide 7.4 Manage /proc file with seq_file
2. ISO-5807-1985
> Modify the descritions of seq_file and flowchart

- lkmpg.tex
In chapter 8, the example code for setting permissions is as follows:
```c
static struct kobj_attribute myvariable_attribute =
__ATTR(myvariable, 0660, myvariable_show, (void *)myvariable_store);
```
We have two options:
1. Instruct users to access the file with `sudo`.
2. Relax the permission setting to 0666.
This commit adopts the sudo method to maintain security constraints.
> docs: Update example in chapter 8 to use sudo

- lkmpg.tex
Delete the duplicate word "otherwise"
Before and after:
otherwise, otherwise -> otherwise
> Fix a typo

- examples/syscall-steal.c
- lkmpg.tex
The syscall-steal example does't work on my x84 Laptops with kernel 6.1 on Debian and 5.15 on Ubuntu.
As mentioned in  this [answer](https://stackoverflow.com/questions/78599971/hooking-syscall-by-modifying-sys-call-table-does-not-work/78607015#78607015) on stack overflow,  syscall table is no longer used to invoke system call on x86 arch after this [commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1e3ad78334a69b36e107232e337f9d693dcc9df2), which is backed-ported to many LTS kernel versions. So maybe an extra example without using syscall table can make it easy to understand the situation for beginners like me .
> Add system call "stealing" sample using kprobe handler

- lkmpg.tex
Change `return-object programming` to `return-oriented programming` in timer API section.
This was mentioned [here](https://github.com/sysprog21/lkmpg/pull/98#discussion_r704877998) but didn't make it into the final revision.
> Correct return-object to return-oriented programming

- examples/sleep.c
There is a subtle bug that if the atomic flag changes between the time it was checked and the second time it was checked, sleep.c would potentially block a process that had specified `O_NONBLOCK`. This fixes the bug by using `atomic_cmpxchg` instead of `atomic_read`.
> Fix: blocking O_NONBLOCK process bug in sleep.c

- examples/procfs1.c
proc_remove does nothing when the argument is NULL[1]. We don't need proc_remove after proc_create failed.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/proc/generic.c#n789
> Remove the redundant code

- examples/procfs2.c
The procfile_write prints the content what user writes into. However, when the content size is greater than or equal to PROCFS_MAX_SIZE, procfile_write will print nothing, because the index for appending the tail NULL character will be modulo to 0.
So, I modify the code with 1. restrict the max acceptable content size to (PROCFS_MAX_SIZE - 1), left a space for NULL character 2. discard the modulo because we already restrict the max size to (PROCFS_MAX_SIZE - 1)
> Fix a wierd behavior of a function

- examples/hello-sysfs.c
The function pointer type of myvariable_store is incompatible with the store member of struct kobj_attribute[1]. So, if we omit the type conversion (void *), we will meet a compilation error. This patch corrects the function declaration and removes the type conversion.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/kobject.h#n139
> Correct the function type

- examples/vinput.c
After class_register failure, the wrong function class_unregister was used. The correct cleanup function should be unregister_chrdev, as register_chrdev was used before class_register.
> Fix incorrect failure handling in vinput_init

- examples/vinput.c
In the export_store function, when vinput_register_vdevice fails, the current error handling process calls device_unregister followed by vinput_destroy_vdevice. However, the device_unregister here triggers its release function, which already includes a call to vinput_destroy_vdevice. As a result, vinput_destroy_vdevice is called twice. Since vinput_destroy_vdevice contains module_put, this double call must be avoided to prevent potential reference count issues.
> Fix potential reference count leak in vinput

- examples/vinput.c
In the export_store function, the error handling paths followed a successful vinput_alloc_vdevice call are missing a corresponding input_free_device call. Since vinput_alloc_vdevice internally calls input_allocate_device, and input_register_device has not been called yet, input_free_device should be used to properly free the allocated input_device struct in this scenario[1].
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/input/input.c#n2094
> Fix potential memory leak in vinput

- examples/hello-sysfs.c
Previously, the code did not call kobject_put when sysfs_create_file
failed, leading to a potential memory leak. This commit adds the missing
kobject_put to ensure proper resource cleanup.
> Fix missing function call in error handling path

- lkmpg.tex
According to [GNU Make Manual](https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html),
Recursive make commands should always use the variable `MAKE`, not the explicit command name `make`.
> Replace make with $(MAKE) in Makefile

- lkmpg.tex
In some commands such as `lsmod`, root permission is not required.
> Remove unnecessary sudo

- examples/other/cat_nonblock.c
In `cat_nonblock.c`, function call of `close()` is missing, which could lead to resource leak. Besides, using `EXIT_FAILURE` macro defined in stdlib.h provides better readability.
> Add missing close() and use EXIT_FAILURE macro in cat_nonblock.c

- .ci/non-working
- .ci/static-analysis.sh
- .github/workflows/status-check.yaml
For callback functions, we may not expect to changes their prototypes, and this commit skips the corresponding checks.
> CI: Skip style with Cppcheck

- examples/bh_threaded.c
- examples/bottomhalf.c
- examples/intrpt.c
gpio_request_array() and gpio_free_array() were
removed in Kernel v6.10-rc1. Use gpio_request()
and gpio_free() instead to make the example run
successfully on v6.10+.
> Allow GPIO example built with Linux v6.10+

- examples/devicemodel.c
Since commit 0edb555 ("platform: Make platform_driver::remove() return void"), the original `platform_driver::remove()` function returned an integer value, usually an error code. This made driver developers think that errors were properly handled. However, the driver core does not stop the device removal process based on the error code, so the error code did not serve its intended purpose. Therefore, the return type was changed to `void` to avoid potential issues.
Make the devicemodel example run successfully on Linux v6.11+.
> Allow devicemodel built with Linux v6.11+

- examples/bottomhalf.c
This PR addresses issue #191 by moving the blocking msleep() call from a tasklet (atomic context) to a workqueue (process context). 
This change prevents kernel crashes due to sleeping in atomic context, while still preserving the immediate LED control logic in the ISR. 
This pull request refactors the kernel's bottom-half processing by replacing tasklets with workqueues, resolving issue #191. It prevents kernel crashes from sleeping in atomic context while ensuring immediate LED control in the ISR. Function names have been updated to reflect these changes.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward and well-documented, making the review …
> Fix bottom-half processing by transitioning to workqueue

- .ci/non-working
- examples/Makefile
- examples/led.c
- lkmpg.tex
Add an LED driver example using GPIO and add related knowledge.
Test detail:
- Tested on Raspberry Pi 5B with Raspberry Pi OS (Debian 12, Linux version 6.12.1-v8-16k+)
- Verify that LED sample compiles and loads successfully
- Verify that LED turns on and off sucessfully 
This pull request introduces a new LED driver example for the Raspberry Pi 5B, featuring a new source file 'led.c' for GPIO control. The Makefile has been updated accordingly, and comprehensive documentation on GPIO and LED control has been added to 'lkmpg.tex'. The implementation has been successfully tested on the Raspberry Pi 5B.
<br>
<br>
<br>
<br>
</div>
> Add an LED driver example using GPIO

- examples/chardev.c
- examples/chardev2.c
- examples/static_key.c
Remove unnecessary definition of SUCCESS, as returning 0 already indicates successful execution. 
This pull request enhances code clarity by removing redundant definitions of SUCCESS across three files and replacing them with 0. This simplification contributes to a cleaner and more maintainable codebase.
<br>
<br>
<br>
<br>
</div>
> Remove redundant code

- lkmpg.tex
Explain the behavior and use cases of spin_lock(), spin_lock_irq(), , spin_lock_irqsave() and spin_lock_bh(). 
This pull request enhances the documentation for spinlock functions in the Linux kernel, clarifying the differences and use cases for spin_lock(), spin_lock_irq(), spin_lock_irqsave(), and spin_lock_bh(). These improvements aim to provide better guidance for developers in real-time Linux environments.
<br>
<br>
<br>
<br>
</div>
> Clarify usage differences between spinlock functions

- lkmpg.tex
A repeated "the" appeared in a sentence describing legacy IRQ flags. 
This pull request improves documentation by removing a duplicate word in a comment regarding legacy IRQ flags, enhancing clarity without affecting functional code.
<br>
<br>
<br>
<br>
</div>
> Remove duplicate word in IRQ flag comment

- lkmpg.tex
Replaced "for specify" with "to specify" in the explanation of IRQ flags. 
This pull request corrects a grammatical error in the documentation regarding IRQ flags, changing 'for specify' to 'to specify'. This enhancement improves the clarity and accuracy of the documentation.
<br>
<br>
<br>
<br>
</div>
> Fix grammar in IRQ flag usage description

- lkmpg.tex
Wrap the type and name in `\cpp|...| `for consistency with other parameters in the sentence. 
This pull request enhances the documentation by improving the formatting of the type 'unsigned int major', ensuring consistency with other parameters and enhancing readability.
<br>
<br>
<br>
<br>
</div>
> Fix formatting of `unsigned int major`

- lkmpg.tex
Update legacy `/dev/hda[1-3]` device file example to `/dev/sda[1-3]` to match modern Linux systems. Adjust major number from 3 to 8 accordingly and remove outdated reference to IDE devices.
[Parallel ATA](https://en.wikipedia.org/wiki/Parallel_ATA)
> With [Western Digital](https://en.wikipedia.org/wiki/Western_Digital)'s withdrawal from the PATA market, hard disk drives with the PATA interface were no longer in production after December 2013 for other than specialty applications.[[31]](https://en.wikipedia.org/wiki/Parallel_ATA#cite_note-32) 
This pull request updates 'lkmpg.tex' documentation to align with modern Linux device file conventions, replacing outdated '/dev/hda[1-3]' references with '/dev/sda[1-3]' and adjusting the major number …
> Update device file example from hda to sda

- lkmpg.tex
Remove the redundant `kmod` installation since it is already installed earlier. Also replace the hardcoded kernel version with `'uname -r'` to improve portability and compatibility with modern Linux distributions. 
This pull request enhances the kernel header installation documentation by eliminating the redundant `kmod` installation and using a dynamic command with `uname -r` instead of a hardcoded kernel version, improving clarity and compatibility. It also updates the installation documentation for better portability across Linux distributions.
<br>
<br>
<br>
<br>
</div>
> Update kernel header install command for clarity

- lkmpg.tex
Replaced the informal message with a formal description to improve
tone and maintain consistency in documentation. 
This pull request enhances document readability and consistency in 'lkmpg.tex' by replacing raw inline messages with LaTeX-style double quotes and an informal example with a more formal description, ensuring correct rendering in generated documents and maintaining a professional standard.
<br>
<br>
<br>
<br>
</div>
> Rephrase informal example in module section

- lkmpg.tex
Replaced "IRQ's" with "IRQs" to use correct grammar.
[Interrupt request](https://en.wikipedia.org/wiki/Interrupt_request)
> Typically, on systems using the [Intel 8259](https://en.wikipedia.org/wiki/Intel_8259) PIC, 16 **IRQs** are used. **IRQs** 0 to 7 are managed by one Intel 8259 PIC, and **IRQs** 8 to 15 by a second Intel 8259 PIC.  
This pull request corrects a grammatical error in the documentation by changing 'IRQ's' to 'IRQs', enhancing clarity and professionalism. Although minor, this update is crucial for maintaining accurate technical writing.
<br>
<br>
<br>
<br>
</div>
> Fix incorrect plural form of IRQ

- lkmpg.tex
Change "The drivers needs" to "The driver needs" to correct a subject-verb disagreement and improve readability. 
This pull request corrects a grammatical error in the documentation for the virtual input device driver section, improving clarity by changing 'The drivers needs' to 'The driver needs'. No other modifications were made.
<br>
<br>
<br>
<br>
</div>
> Fix grammar in virtual input device driver section

- lkmpg.tex
Changed "a user read" to "a user reads" for correct grammar in documentation. 
This pull request corrects a grammatical error in the documentation regarding the /proc file system, changing 'a user read' to 'a user reads' for improved clarity. No other modifications were made, focusing solely on documentation enhancement.
<br>
<br>
<br>
<br>
</div>
> Fix grammar in the /proc file system section

- lkmpg.tex
Improve wording and grammar in the tasklet section. Reflect current discussion on tasklet deprecation and correct Linux kernel casing. 
This pull request enhances the documentation for tasklets in the Linux kernel, clarifying their limitations and addressing discussions on potential deprecation. It also corrects the casing of 'Linux' for consistency throughout the document.
<br>
<br>
<br>
<br>
</div>
> Clarify tasklet limitations and deprecation plans

- examples/led.c
Kernel 6.4+ sets .owner automatically. Remove manual assignment to avoid build issues and keep compatibility with older versions.
Reference : sysprog21/simrupt#12 
This pull request updates the LED device driver for kernel compatibility by removing the manual assignment of the .owner field for kernel versions 6.4 and above, preventing build issues while ensuring adherence to new kernel standards.
<br>
<br>
<br>
<br>
</div>
> Drop .owner for kernel >= 6.4

- examples/devicemodel.c
- examples/static_key.c
- examples/syscall-steal.c
The condition ">=" is used to align all version checks, improving code consistency and readability. 
This pull request enhances code consistency and readability by aligning the version check for the class_create function in static_key.c with chardev.c and standardizing version checks across multiple files. The condition was modified from '<' to '>=', improving overall code quality, logical consistency, and maintainability across related files.
<br>
<br>
<br>
<br>
</div>
> Align version check

- lkmpg.tex
Since the primary focus of Chapter 12 is on the techniques used to synchronize access to shared resources in a multi-CPU environment, changing the title to 'Synchronization' would better reflect the content and improve clarity. 
This pull request updates the title of Chapter 12 from 'Avoiding Collisions and Deadlocks' to 'Synchronization' to enhance clarity and better reflect the chapter's focus on synchronization techniques in multi-CPU environments.
<br>
<br>
<br>
<br>
</div>
> Change title to 'Synchronization' for better alignment with content

- lkmpg.tex
Add documentation for Linux kernel mutexes, detailing ownership, initialization, and the behavior of _interruptible, nested and try-lock variants for synchronization. 
This pull request enhances the documentation for mutexes in the Linux kernel, detailing mutex ownership, initialization, and the behavior of various mutex functions. These improvements aim to assist developers in better understanding kernel synchronization.
<br>
<br>
<br>
<br>
</div>
> Add explanation of mutexes and function variants

- lkmpg.tex
Close #270 
This pull request enhances documentation on system calls by adding notes about a feature unavailable since Linux version 6.9. It clarifies the impact of a specific commit that altered the system call table for security, improving understanding of kernel programming risks.
<br>
<br>
<br>
<br>
</div>
> syscall: Add description of unavailable since v6.9

- examples/sched.c
Since the example in Chapter 15.2 demonstrates the use of work queues in kernel modules, improving its reliability with proper error handling and cleanup logic helps reflect best practices in modern kernel development. This change enhances safety by preventing null pointer dereference during allocation failure and ensuring all work is completed before module unload.
This pull request improves the example in Chapter 15.2, "Work queues", by adding error handling for alloc_workqueue() and ensuring flush_workqueue() is called before destroy_workqueue() in the module exit path. These changes align the code with kernel best practices, prevent common pitfalls like null pointer dereference, and make the example safer for readers and learners on modern kernels.
These changes improve robustness in …
> Improve example in 15.2 Work queues with error handling and cleanup

- examples/bh_threaded.c
Ensuring the free_irq function properly releases IRQs for buttons, call free_irq() with button's device handler instead of NULL. 
This pull request resolves a kernel panic issue by ensuring the free_irq function is called with the correct device handler when unloading the bh_threaded module. This enhancement improves the stability and reliability of IRQ management for button devices.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward and primarily focus on fixing a specific issue, making the review process relatively simple.
</div>
> Fix kernel panic when unload bh_threaded module

- .ci/non-working
- examples/Makefile
- examples/dht11.c
- lkmpg.tex
Use GPIO to communicate with the DHT11 sensor.
Test detail:
- Tested on Raspberry Pi 5B with Raspberry Pi OS (Debian 12, Linux version 6.6.74)
- Verify that the DHT11 driver compiles and loads successfully
- Verify that temperature and humidity data can be read correctly from the DHT11 sensor 
This pull request introduces a new DHT11 sensor driver example utilizing GPIO for communication, with updates to the Makefile for proper compilation. The implementation includes functions for reading sensor data and has been tested on a Raspberry Pi 5B, confirming accurate temperature and humidity retrieval.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward …
> Add a DHT11 Sensor Driver Example Using GPIO

- examples/devicemodel.c
The previous implementation of devicemodel_remove used conditional compilation to switch between void and int return types based on the kernel version. While functionally correct, the interleaved `#if/#endif` blocks made the logic harder to follow.
This refactor cleanly separates the two function definitions using a full `#if/#else` block around the entire function.
No functional behavior is changed.
Close: #313  
This pull request refactors the device model implementation, enhancing the readability of the devicemodel_remove function. It replaces conditional compilation with a clearer structure that separates function definitions by kernel version, without changing the functional behavior of the code.
<br>
<br> …
> examples: Refactor device model with version-based split

- lkmpg.tex
There is a missing 'is' in the sentence, add it. 
This pull request corrects a minor grammatical error in the documentation by adding the word 'is', enhancing clarity and readability without affecting technical content.
</div>
> Add missing 'is'

- .gitignore
- examples/hello-1.c
- lkmpg.tex
- Add more contents that cursor IDE generates to `.gitignore`
- According to the [Legal writing advice](https://www.slaw.ca/2011/07/27/grammar-legal-writing/#:~:text=%2A%20and%2For.%20Avoid%20this%20Janus,), the "or" word already means "X or Y or both", so we don't need to write "and" again.
- According to [merriam-webster dictionary](https://www.merriam-webster.com/dictionary/failing%20that#:~:text=formal), "Failing that" is a formal idiom, so I correct "Failing this" with that.
- Add some punctuation:
- Add double quotes to make sentences more clear
- Add comma before "for example" because of [this page](https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/punctuation/commas#:~:text=Use%20commas%20with%20the%20phrase,%E2%80%98for%20example%E2%80%99)
- Use more formal word …
> Improve grammar and .gitignore

- lkmpg.tex
The original sentence was ungrammatical and slightly unclear.
This patch improves the article usage, verb tense, and phrasing
to ensure clarity and correctness. 
This pull request enhances the clarity and grammatical correctness of the API coexistence documentation in the Linux kernel. It improves phrasing and verb tense for better understanding, making the documentation more precise and easier to read.
</div>
> Fix grammar and tense in API coexistence explanation

- examples/chardev.c
The original comment referred to /dev/hello, but the actual device created by the module is /dev/chardev.
In addition, writing to /dev/chardev using output redirection (>) typically fails due to insufficient permissions, since redirection is handled by the shell before sudo applies. As a result, the device_write() function may never be entered.
This change updates the comment to recommend using a pipe with `sudo tee`, which correctly elevates privileges and allows the write operation to reach the driver. 
This pull request clarifies the write operation for the /dev/chardev device by correcting the previous comment that referenced /dev/hello. It now includes guidance on using a pipe with `sudo tee` …
> Clarify write usage in comment for /dev/chardev

- lkmpg.tex
This pull request corrects a grammatical error in the documentation of the kernel compilation process, changing 'as following' to 'as follows'. This modification enhances the clarity and professionalism of the documentation.
</div>
> Fix grammer

- examples/chardev.c
- examples/chardev2.c
- examples/procfs3.c
- examples/sleep.c
- examples/static_key.c
- examples/vinput.c
- lkmpg.tex
This commit removes all instances of try_module_get(THIS_MODULE) and corresponding module_put(THIS_MODULE) calls from example modules. This pattern is considered unsafe because:
- The kernel automatically manages module reference counting during file operations
- Manual reference counting within a module's own code can lead to race conditions
- It is redundant and unnecessary for proper module operation
It also updates documentation to:
- Remove references to try_module_get/module_put functions
- Add note explaining why these functions should be avoided
- Keep only module_refcount() as a safe display function
Close #52 
This pull request enhances kernel module safety by removing unsafe functions …
> Remove unsafe try_module_get(THIS_MODULE)

- lkmpg.tex
This commit resolves confusion where users expected module output to appear directly in terminal. It also updates documentation to clearly explain that:
- Module output goes to kernel log ring buffer, not console
- Use 'dmesg' to view module messages
- Terminal environment doesn't affect where output goes
- Provides concrete examples in hello world section
Close #171 
This pull request enhances the documentation for kernel module output, clarifying that messages are directed to the kernel log ring buffer rather than the terminal. It provides clear instructions for using the 'dmesg' command to view these messages and includes concrete examples in the hello world section to reduce user confusion. …
> Clarify kernel module output goes to dmesg, not console

- examples/sleep.c
Use "/proc" when the comment refers to the actual file (/proc/sleep) and keep "proc" when it denotes the procfs mechanism or related helper APIs. This makes the documentation consistent and avoids ambiguity between a file path and the proc filesystem itself. 
This pull request enhances the clarity of comments in 'examples/sleep.c' by ensuring consistent references to the file path '/proc' and the procfs mechanism. This improves documentation quality and reduces ambiguity.
</div>
> examples/sleep: clarify /proc vs procfs wording

- examples/bottomhalf.c
- lkmpg.tex
There are two commits:
1. Remove unused DECLARE_TASKLET_OLD macro (no longer needed after switching to workqueues).
2. Update description to mention workqueues instead of tasklets.
Keep the code and docs consistent, avoiding confusion.
> Bottomhalf example cleanup and doc update
