sysprog21/lkmpg

lkmpg.tex
Collect very minor fixes into a single patch to be merged biweekly(?).
=> Typo at 0.7.3 Manage /proc file with seq_file

lkmpg.tex
Little changes regarding the use of `sudo`.
=> Fix command style

lkmpg.tex
=> 🐛 [fix] add package xparse

lkmpg.tex
=> fix minor typo

examples/sleep.c
I think the filename should be /proc/sleep
=> Fix init message

lkmpg.tex
Fix some typos and add the missing punctuation.
=> Fix wording

examples/hello-1.c, examples/hello-2.c, examples/hello-3.c, examples/hello-4.c, lkmpg.tex
Hi,
Please find in this PR a series of (hopefully) obvious typo fixes, along with small improvements. I've taken notes along the way during the last two weeks, but I've had to rebase to catch up with recent changes. I hope I didn't break any tentative improvements while doing so…
Thanks for considering!
Cheers,
Cyril.
=> Proofreading and small improvements

html.cfg
You can check it in [https://fennecj.github.io/lkmpg/](https://fennecj.github.io/lkmpg/)
=> Add pdf download link in html only

examples/kbleds.c
Update below file path in comment of example/kbleds.c to kernel version v5.x:
1. drivers/char/vt_ioctl.c -> drivers/tty/vt/vt_ioctl.c
2. drivers/char/keyboard.c -> drivers/tty/vt/keyboard.c
=> Update some file path to kernel v5.x in comment of example/kbleds.c

lkmpg.tex
In section 0.4.1, changing you to your.
=> Fixed typo

html.cfg
The patch using a CDN script to render a pretty Github button.
Close #84
=> Add a Github button in html files

examples/.clang-format, examples/Makefile, examples/bottomhalf.c, examples/chardev.c, examples/chardev.h, examples/chardev2.c, examples/cryptosha256.c, examples/cryptosk.c, examples/devicemodel.c, examples/example_atomic.c, examples/hello-2.c, examples/hello-3.c, examples/hello-4.c, examples/hello-5.c, examples/hello-sysfs.c, examples/intrpt.c, examples/ioctl.c, examples/kbleds.c, examples/print_string.c, examples/procfs1.c, examples/procfs2.c, examples/procfs3.c, examples/procfs4.c, examples/sched.c, examples/sleep.c, examples/syscall.c
Except the indention is four spaces rather than tabs
for sticking to compact layout of source listing,
we should follow others rules.
The Linux coding style
- https://www.kernel.org/doc/html/latest/process/coding-style.html
=> Follow the Linux coding style

.ci/static-analysis.sh
Sparse[1] is a semantic parser for C language, it can find out the
potential problem of the example code.
[1] https://www.kernel.org/doc/html/latest/dev-tools/sparse.html
=> CI: Integrate the Sparse into the CI pipeline

lkmpg.tex
Add `PWD := $(CURDIR)` in Makefile and the explanation about `sudo make` when only having `PWD` in Section 4.
=> Update Makefile and Add explanation in section 4

.ci/non-working, .mailmap, contrib.tex, examples/.clang-format, examples/Makefile, examples/vinput.c, examples/vinput.h, examples/vkbd.c, lkmpg.tex, scripts/Contributors, scripts/Include
Add the new section of device driver, vinput[1].
[1] https://github.com/sysprog21/vinput
=> Introduce Virtual Input Device Driver

examples/chardev2.c
After forking, Each file descriptor in the child refers to the same
open file description as the parent. So when calling open() before
fork(), the child can access the device file without checking by
exclusive access in device_open(). It may cause race conditions
in device_ioctl().
Because of that, it is unnecessary to check the multiple access
in device_open(). It just needs check in device_ioctl(), since
read(), write(), seek() system call are atomic [1][2].
- https://github.com/sysprog21/lkmpg/issues/148
[1] https://lore.kernel.org/lkml/53022DB1.4070805@gmail.com/
[2] https://www.kernel.org/doc/html/latest/filesystems/files.html
=> Fix potential concurrent problems in chardev2.c

lkmpg.tex
=> Relocate Archlinux code snippet to avoid confusion

examples/completions.c, examples/cryptosha256.c, examples/cryptosk.c, examples/devicemodel.c, examples/example_atomic.c, examples/example_mutex.c, examples/example_rwlock.c, examples/example_spinlock.c, examples/example_tasklet.c, examples/ioctl.c
=> example: Add missing __init/__exit

lkmpg.tex
The verb 'suggest' is used with the gerund form.
=> Fix grammar

lkmpg.tex
Thank you for the helpful book! I found two typos in Sec. 5, which I hope to fix like this.
=> Fix two typos in Preliminaries section
